name: Second Workflow
on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  setup-job:
    runs-on: ubuntu_latest
    steps:
      - name: 'Retrieve code'
        uses: actions/checkout@v4.1.7
      - name: Install NodeJS
        uses: actions/setup-node@v4
      - name: Install dependencies
        run: npm ci  #pip install -r requirements.txt
      - name: Run tests
        run: npm test
  deploy:
    needs: [ setup-job ]
    runs-on: ubuntu-latest
    steps:
      - name: 'Retrieve code'
        uses: actions/checkout@v4.1.7
      - name: Install NodeJS
        uses: actions/setup-node@v4
      - name: Build project
        run: npm run build
      - name: Deploy
        run: echo "Deploying..."